### ISSUE TITLE
An embarrassing issue

### ISSUE THREAD

**Issue by lbh2001** [apache/dubbo-go-pixiu#165]
Sorry for my disturbing. I'm a student, and I'm interested in dubbo-go-pixiu. Besides, I'm also planning to apply for the [ospp](https://summer.iscas.ac.cn/#/org/orgdetail/dubbogo) program instructed by @xiaoliu10 but I have some troubles. I've sent an email but didn't receive after three days. So I'll really appreciate it if I could get in touch with the mentor @xiaoliu10 . Sorry for my bothering again!

**Comment by xiaoliu10** [comment]
hi, my fault, have you found the subject now?

**Comment by xiaoliu10** [comment]
my dingding num 18721825717 @lbh2001

**Comment by lbh2001** [comment]
> my dingding num 18721825717 @lbh2001

Fine.
