### ISSUE TITLE
add more integrate test

### ISSUE THREAD

**Issue by xiaoliu10** [apache/dubbo-go-pixiu#184]
**What would you like to be added**:
 now, we have one integrate test example, add more

**Why is this needed**:

**Comment by geegatomar** [comment]
Hi, can I work on this? Can I please get more information on what is the requirement precisely?

**Comment by mark4z** [comment]
> Hi, can I work on this? Can I please get more information on what is the requirement precisely?

Yeah, U can join our dingtalk first, the number is 31203920

**Comment by ma642** [comment]
done
