### ISSUE TITLE
Reason: CORS header ‘Access-Control-Allow-Origin’ missing

### ISSUE THREAD

**Issue by tang05709** [apache/dubbo-go-pixiu#246]
config.yml

static_resources:
  listeners:
    - name: "net/http"
      address:
        socket_address:
          protocol_type: "HTTP"
          address: "0.0.0.0"
          port: 8884
      filter_chains:
        - filter_chain_match:
            domains:
              - api.dubbo.com
              - 0.0.0.0
          filters:
            - name: dgp.filters.http_connect_manager
              config:
                route_config:
                  routes:
                    - match:
                        prefix: "/api/v1"
                        headers:
                          - name: "Access-Control-Allow-Origin"
                            value: "*"
                      route:
                        cluster: "Besass"
                        cluster_not_found_response_code: 505
                        cors:
                          allow_origin:
                            - "*"
                          enabled: true
      config:
        idle_timeout: 5s
        read_timeout: 5s
        write_timeout: 5s
  clusters:
    - name: "test"
      lb_policy: "RoundRobin"
      registries:
        "nacos1":
          protocol: "nacos"
          timeout: "3s"
          address: "127.0.0.1:8848"
          username: "nacos"
          password: "nacos"
  timeout_config:
    connect_timeout: "5s"
    request_timeout: "10s"
  shutdown_config:
    timeout: "60s"
    step_timeout: "10s"
    reject_policy: "immediacy"

**What happened**:
vue request error:
Reason: CORS header ‘Access-Control-Allow-Origin’ missing

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by MasterKenway** [comment]
This problem was caused by unfinished HttpConnectionManager [](https://github.com/apache/dubbo-go-pixiu/issues/237 ), we have notice this problem and will be complete in the next update. Thank you for supporting.

**Comment by MasterKenway** [comment]
pr #249

**Comment by mark4z** [comment]
close via #249
