### ISSUE TITLE
POST请求body丢失问题

### ISSUE THREAD

**Issue by ztelur** [apache/dubbo-go-pixiu#259]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ztelur** [comment]
![image](https://user-images.githubusercontent.com/6263372/134931799-cc113327-66b8-4d26-89a6-338ecc616363.png)
DefaultClient 可能被其他库修改了，引入了 fasthttp，导致body丢失了。

**Comment by ztelur** [comment]
改进方向，在 httpproxy 中声明私有的client，并且将client的相关配置放开为httpproxy的配置项，让用户自行配置
![Uploading image.png…]()

**Comment by baerwang** [comment]
提个问题，如果用户不喜欢自己写客户端的配置信息，是不是可以默认设置为defaultClient，如果用户需要修改的话，用户完全可以自己去写client相关的配置信息，这样的话代码也比较清晰，不用写client的相关配置信息了
