### ISSUE TITLE
k8s 集群内部署的话直接用NumCPU()获取不到真实可用核心数

### ISSUE THREAD

**Issue by ztelur** [apache/dubbo-go-pixiu#313]
https://github.com/apache/dubbo-go-pixiu/blob/develop/cmd/pixiu/pixiu.go#L151

这里是不是有点问题. 在 k8s 集群内部署的话直接用NumCPU()获取不到真实可用核心数. 会导致调度不合理延迟加大.

from others

**Comment by AlexStocks** [comment]
github.com/shirou/gopsutil v3

**Comment by ztelur** [comment]
It seems that gopsutil doesn't work well in k8s too. stackoverflow answer recommand https://github.com/uber-go/automaxprocs. 
```
import _ "go.uber.org/automaxprocs"

func main() {
  // Your application logic here.
}
```
pixiu code is like below

```
	if limitCpuNumber <= 0 {
		runtime.GOMAXPROCS(runtime.NumCPU())
	} else {
		runtime.GOMAXPROCS(int(limitCpuNumber))
	}
```
Do we need assign limitCpuNumber by command argument ?

**Comment by songoow** [comment]
More recommended  use go.uber.org/automaxprocs  which  automatically set GOMAXPROCS according to linux container quota。https://github.com/shirou/gopsutil/blob/master/cpu/cpu.go#L64   which  returns the number of physical  can't fix this. go.uber.org/automaxprocs has been used in dapr ,jaeger to fix the same bug.
