### ISSUE TITLE
pixiu的api-conf.yaml配置简化方案（待议）

### ISSUE THREAD

**Issue by phial3** [apache/dubbo-go-pixiu#338]
提供WEB界面根据已有的服务接口方法去配置path和filter。
1、如何提供服务
（1）使用Go的web框架，比如Gin，但是每个操作对象接口和CURD操作需要自己实现
（2）使用Java微服务提供，框架成熟通用简单，利用 spring-native 和 GraalVM 可以转换Java程序为原生可执行的程序（启动时间和运行性能测试都要优于运行在JVM之上），然后嵌入到pixiu里面即可
2、配置的内容如何存储
（1）使用mysql，需要综合考虑一下
（2）使用H2，轻量级可直接嵌入进去，存储可以持久化到单独的文件，但是存在部分局限，安全性需要考虑
3、提供WEB界面的意义在哪里，或者说有无必要
（1）将主动权交给用户，这个path的配置和过滤规则是可有可无的
（2）对用户来说，可弃用原来手动配置的api-conf文件，不需要用户进入到服务内部去修改
（3）对网关服务来说，该配置可以动态加载，网关服务不会受到用户配置的影响
4、其他
...

（下面是简单做了一个界面：）
![image](https://user-images.githubusercontent.com/27754514/148232252-f6cd6d87-9654-418b-ba97-489db51d3797.png)

**Comment by MasterKenway** [comment]
使用 database 来存配置会不会太重了？

**Comment by mark4z** [comment]
这样吧，仅从功能的角度来说，我看到有几个点:
1.Dubbo API配置的简化/消除，目前其实已经支持了
2.Filter的配置，是Route上挂Filter还是Filter里定义路由，这是个好问题
3.配置的存储问题，这个倾向于ETCD，而且目前负责XDS的大佬已经在做了

**Comment by mark4z** [comment]
@ma642
