### ISSUE TITLE
build a load balance abstraction for invoking request to upstream servers

### ISSUE THREAD

**Issue by ztelur** [apache/dubbo-go-pixiu#366]
**What would you like to be added**:

Add a load balance abstraction for invoking request to upstream servers.

Now, `lb` is just a `cluster` parameter, and is used in `PickOneEndpoint ` function. That's difficult to implement complex load balance strategy.

Refer to `https://github.com/mosn/mosn/blob/master/pkg/upstream/cluster/loadbalancer.go`

**Why is this needed**:

**Comment by mark4z** [comment]
@baerwang

**Comment by baerwang** [comment]
accept
