### ISSUE TITLE
Add call multi cluster

### ISSUE THREAD

**Issue by cityiron** [apache/dubbo-go-pixiu#4]
**What would you like to be added**:
Support backend have more than one register center(multi cluster), may be nacos cluster, zk cluster etc

**Why is this needed**:
When proxy use as a gateway, need call one than one Independent cluster.

**Comment by oaoit** [comment]
maybe backend can register muti center cluster, proxy call one enough.

**Comment by cityiron** [comment]
yes, one is enough
