### ISSUE TITLE
GSoC 2022: Pixiu Sidcar Initializer

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [apache/dubbo-go-pixiu#400]
K8s Initializer was written to automatically add Pixiu as sidecar for the Pod created. Then business services could register Pixiu instead of It in Dubbo cluster by calling Pixiu through fixed interface and communicating with Pixiu through Http interface. Pixiu replaced its communication with Dubbo cluster

So if you are interested in this project and the objective described in the proposal, please leave comments below so we can further exchange opinions.

Please don't forget to apply for GSoC from its official website when the application slot opens.

**Comment by lawrshen** [comment]
I'm interested in this. Should I construct a K8s controller for Pixiu service injection, and modify related communication?
