### ISSUE TITLE
GSoC 2022: Pixiu Metrics Implementation

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [apache/dubbo-go-pixiu#401]
Metrics are an important part of the observability of the underlying software, allowing developers to see how their software is performing and to provide early warning of upcoming problems online.

So if you are interested in this project and the objective described in the proposal, please leave comments below so we can further exchange opinions.

Please don't forget to apply for GSoC from its official website when the application slot opens.

**Comment by mark4z** [comment]
close via https://github.com/apache/dubbo-go-pixiu/pull/480
