### ISSUE TITLE
GSoC 2022: Pixiu Traffic Distribution Mode Implementation

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [apache/dubbo-go-pixiu#402]
The gateway should provides the ability to distribute traffic, which makes it easier to build service o&M capabilities such as Canary testing and blue and green publishing.

So if you are interested in this project and the objective described in the proposal, please leave comments below so we can further exchange opinions.

Please don't forget to apply for GSoC from its official website when the application slot opens.

**Comment by luyi404** [comment]
Hi, I have noticed that this proposal has also appears at `summer-ospp`, and I am really interested in the implementation of traffic distribution. Does this mean that we need to add traffic control-like components to pixiu, such as traffic control, traffic distribution, and exception fusing?
