### ISSUE TITLE
GSoC 2022: Pixiu WASM Plugin Support

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [apache/dubbo-go-pixiu#403]
Pixiu project supports WASM extension, which facilitates the use of WASM mechanism for dynamic capability extension

So if you are interested in this project and the objective described in the proposal, please leave comments below so we can further exchange opinions.

Please don't forget to apply for GSoC from its official website when the application slot opens.

**Comment by mark4z** [comment]
close via https://github.com/apache/dubbo-go-pixiu/pull/469
