### ISSUE TITLE
GSoC 2022: Pixiu Graceful Hot Reload

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [apache/dubbo-go-pixiu#404]
Graceful reload for HTTP/HTTPS proxies, Dubbo/Triple proxies, and for elegant updates for GRPC. We should provides the ability to minimize traffic loss when updating within a specified time.

So if you are interested in this project and the objective described in the proposal, please leave comments below so we can further exchange opinions.

Please don't forget to apply for GSoC from its official website when the application slot opens.

**Comment by mark4z** [comment]
close via https://github.com/apache/dubbo-go-pixiu/pull/474
