### ISSUE TITLE
GSoC 2022: Optimization of Pixiu timeout feature

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [apache/dubbo-go-pixiu#405]
HTTP/HTTPS timeout configurations, Dubbo /triple timeout Settings, GRPC timeout Settings. Provides the ability to return a timeout within a specified time.

So if you are interested in this project and the objective described in the proposal, please leave comments below so we can further exchange opinions.

Please don't forget to apply for GSoC from its official website when the application slot opens.

**Comment by maxingg** [comment]
I'm interested in this. Should I construct a timeout component to be used by any call and method, and specify a time in conf.yaml ?

**Comment by mark4z** [comment]
close via https://github.com/apache/dubbo-go-pixiu/pull/475
