### ISSUE TITLE
大佬们，有计划支持webscoket代理吗

### ISSUE THREAD

**Issue by wujincheng2333** [apache/dubbo-go-pixiu#409]
**What would you like to be added**:

**Why is this needed**:

**Comment by AlexStocks** [comment]
> **What would you like to be added**:
> 
> **Why is this needed**:

有这个计划，已经安排人开发了。你在dubbogo社区群吗？可以找群主我聊下

**Comment by wujincheng2333** [comment]
> > **What would you like to be added**:
> > **Why is this needed**:
> 
> 有这个计划，已经安排人开发了。你在dubbogo社区群吗？可以找群主我聊下

还没加，这几天还在测试

**Comment by wujincheng2333** [comment]
> > **What would you like to be added**:
> > **Why is this needed**:
> 
> 有这个计划，已经安排人开发了。你在dubbogo社区群吗？可以找群主我聊下

两个二维码都过期了

**Comment by AlexStocks** [comment]
> > > **What would you like to be added**:
> > > **Why is this needed**:
> > 
> > 
> > 有这个计划，已经安排人开发了。你在dubbogo社区群吗？可以找群主我聊下
> 
> 两个二维码都过期了

You can search the group number 23331795 .

**Comment by wujincheng2333** [comment]
> > > > **What would you like to be added**:
> > > > **Why is this needed**:
> > > 
> > > 
> > > 有这个计划，已经安排人开发了。你在dubbogo社区群吗？可以找群主我聊下
> > 
> > 
> > 两个二维码都过期了
> 
> You can search the group number 23331795 .

大佬，提交申请了

**Comment by mark4z** [comment]
有没有更详细的需求，除了基本的websocket

**Comment by wujincheng2333** [comment]
> 有没有更详细的需求，除了基本的websocket

1. 内容可拦截处理，加解密之类的。
2. 转发消息大小可控。
3. 支持网关鉴权。
4. 支持二进制消息。
5. 首次握手支持重试（避免注册中心更新延时导致连接拒绝）。

**Comment by mark4z** [comment]
确认一下，是websocket to websocket，而不是http to websocket对吗

> > 有没有更详细的需求，除了基本的websocket
> 
> 
> 
> 1. 内容可拦截处理，加解密之类的。
> 
> 2. 转发消息大小可控。
> 
> 3. 支持网关鉴权。
> 
> 4. 支持二进制消息。
> 
> 5. 首次握手支持重试（避免注册中心更新延时导致连接拒绝）。

**Comment by wujincheng2333** [comment]
> 确认一下，是websocket to websocket，而不是http to websocket对吗
> 
> > > 有没有更详细的需求，除了基本的websocket
> > 
> > 
> > 
> > 1. 内容可拦截处理，加解密之类的。
> > 2. 转发消息大小可控。
> > 3. 支持网关鉴权。
> > 4. 支持二进制消息。
> > 5. 首次握手支持重试（避免注册中心更新延时导致连接拒绝）。

是的

**Comment by mark4z** [comment]
请问鉴权什么什么形式的@wujincheng2333

**Comment by wujincheng2333** [comment]
> 请问鉴权什么什么形式的@wujincheng2333

握手阶段,获取url参数之类的鉴权
