### ISSUE TITLE
[ASoC 2022] Exploration of Sidecar Mode of Pixiu

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [apache/dubbo-go-pixiu#430]
### Background

This is an basic subject of [[ASoC 2022](https://opensource.alibaba.com/asoc2022)](https://opensource.alibaba.com/asoc2022) and https://github.com/apache/dubbo/issues/10088 .

We need to implement a k8s initializer, automatically adding Pixiu as a sidecar for the Pod we created. Then the business service can register with the Dubbo cluster by calling Pixiu through the fixed interface instead of it, and communicate with the Pixiu through the Http interface, and Pixiu communicates with the Dubbo cluster instead of business service.

## Difficulty

Difficult

## Mentor

- @marlonfan 

## Output Requirement

1.  Pixiu registers itself with a dubbo cluster in place of a business service
2. refactor at least one old request handle implement such as http to dubbo with the unified request processing mechanism with timeout

## 背景

这是一个[[阿里巴巴编程之夏 2022](https://opensource.alibaba.com/asoc2022)](https://opensource.alibaba.com/asoc2022) 的基础课题 https://github.com/apache/dubbo/issues/10088 。

Pixiu Sidecar 模式探索

我们需要编写 k8s initializer，为创建的 Pod 自动添加 Pixiu 作为sidecar，然后业务服务可以通过固定接口调用 Pixiu 代替其注册到 Dubbo 集群中，通过 Http 接口和 Pixiu 通讯， Pixiu 代替其与 Dubbo 集群通讯

## 难度

困难

## 导师

- @marlonfan 

## 产出要求

1. 形成 Pixiu 代替业务服务注册自身到 dubbo 集群的能力；
2. Pixiu 作为sidecar自动注入到 Pod 中。

**Comment by thenicetgp** [comment]
interesting,let me try
