### ISSUE TITLE
[ASoC 2022] Optimization of Pixiu timeout feature

### ISSUE THREAD

**Issue by ztelur** [apache/dubbo-go-pixiu#431]
### Background

This is an basic subject of [[ASoC 2022](https://opensource.alibaba.com/asoc2022)](https://opensource.alibaba.com/asoc2022) and https://github.com/apache/dubbo/issues/10088 .

HTTP/HTTPS timeout configurations, Dubbo /triple timeout Settings, GRPC timeout Settings. Provides the ability to return a timeout within a specified time.

## Difficulty

Medium

## Mentor

- @mark4z [mark4z@apache.org](mailto:mark4z@apache.org)

## Output Requirement

1. form a unified request processing mechanism with timeout
2. refactor at least one old request handle implement such as http to dubbo with the unified request processing mechanism with timeout

## 背景

这是一个[[阿里巴巴编程之夏 2022](https://opensource.alibaba.com/asoc2022)](https://opensource.alibaba.com/asoc2022) 的基础课题 https://github.com/apache/dubbo/issues/10088 。

优化 Pixiu 请求处理超时机制

配置 HTTP/HTTPS、Dubbo、GRPC 超时配置，可以构造优雅的统一策略，提供按照指定超时时间返回的能力。

## 难度

中等

## 导师

- @mark4z 

## 产出要求

1. 形成一套统一的处理带超时的请求处理机制；
2. 使用上述机制至少重构一个旧的请求处理实现，比如说 http to dubbo 请求的处理逻辑实现。

Please don't forget to apply for GSoC from its official website when the application slot opens.

**Comment by yclchuxue** [comment]
Hi! Has anyone followed up on this project? I want to try.

**Comment by mark4z** [comment]
> Hi! Has anyone followed up on this project? I want to try.

Hey,join our dingtalk group : 31203920
