### ISSUE TITLE
[ASoC 2022] Pixiu Metrics Implementation

### ISSUE THREAD

**Issue by ztelur** [apache/dubbo-go-pixiu#433]
### Background

This is an basic subject of [[ASoC 2022](https://opensource.alibaba.com/asoc2022)](https://opensource.alibaba.com/asoc2022) and https://github.com/apache/dubbo/issues/10088 .

Metrics are an important part of the observability of the underlying software, allowing developers to see how their software is performing and to provide early warning of upcoming problems online.

## Difficulty

Medium

## Mentor

- @PhilYue 

## Output Requirement

1.  Provides unified metrics metric calculation and escalation implementation
2. Add calculations for simple metrics such as request processing latency, request processing QPS, and so on for Pixiu

## 背景

这是一个[[阿里巴巴编程之夏 2022](https://opensource.alibaba.com/asoc2022)](https://opensource.alibaba.com/asoc2022) 的基础课题 https://github.com/apache/dubbo/issues/10088 。

提供统一的 metrics 指标计算和上报实现，为 Pixiu 添加诸如请求处理延时、请求处理 QPS 等简易指标的计算

## 难度

中等

## 导师

- @PhilYue 

## 产出要求

1. 提供统一的 metrics 指标计算和上报实现；
2. 为 Pixiu 添加诸如请求处理延时、请求处理 QPS 等简易指标的计算

**Comment by TheR1sing3un** [comment]
Hello, where can I contact the mentor?
