### ISSUE TITLE
No filters in conf.yaml

### ISSUE THREAD

**Issue by maxingg** [apache/dubbo-go-pixiu#441]
**What happened**:
When no filter is configured in conf.yaml, requests which are listened by the listener are definitely not processed and forwarded.

**What you expected to happen**:
Therefore, the return status code should not be "200 OK", and the message body should not be simply null.

![image](https://user-images.githubusercontent.com/32018399/172994443-fd8a21a2-cd0d-453b-aeaf-262b08094044.png)
![image](https://user-images.githubusercontent.com/32018399/172994464-24e5c19d-6420-48bb-a5f5-ef4295ea1cfc.png)

**Comment by baerwang** [comment]
Can take a look at the config file?
