### ISSUE TITLE
develop分支上，代码重复（完全一模一样代码）

### ISSUE THREAD

**Issue by drama10096** [apache/dubbo-go-pixiu#445]
在pkg/adapter/dubboregistry/registry/listener.go里面有

type Listener interface {
	Close()
	WatchAndHandle()
}

在pkg/remote/zookeeper/client.go也有

type Listener interface {
	Close()
	WatchAndHandle()
}

**Comment by MasterKenway** [comment]
refactor needed [WIP]

**Comment by mark4z** [comment]
@drama10096 May u refactor it?

**Comment by SunnyBoy-WYH** [comment]
how about move thie listener.go refactor to dir : "pkg/adapter/dubboregistry/listener.go"? so we can remove the Listener interface defined in "pkg/remote/zookeeper/client.go"

**Comment by PhilYue** [comment]
@drama10096 社区已经记录了这个优化项，接下来会根据项目计划去推进重构优化代码，欢迎加入社区，有什么最新进展会在群里同步大家。

**Comment by PhilYue** [comment]
> 

先暂时关闭了，之后会计划小重构迭代
