### ISSUE TITLE
server_handler.go OnMessage pkg is judge false

### ISSUE THREAD

**Issue by cityiron** [apache/dubbo-go-pixiu#457]
**What happened**:

When run dubbo2http samples use develop branch,  will hit error log like follow code:
```go
	decodeResult, drOK := pkg.(remoting.DecodeResult)
	if !drOK {
		logger.Errorf("illegal package{%#v}", pkg)
		return
	}
```
this pkg object is `*remoting.DecodeResult`

**What you expected to happen**:

drOk will true, and run continue.

**How to reproduce it (as minimally and precisely as possible)**:

Just run pixiu, samples/dubbohttpproxy/server/http/server.go, and run dubbo2http_test.go.

**Comment by cityiron** [comment]
Just change to 
```go
	decodeResult, drOK := pkg.(*remoting.DecodeResult)
	if !drOK {
		logger.Errorf("illegal package{%#v}", pkg)
		return
	}
```
, run success.

**Comment by complone** [comment]
i want to try to fix it

**Comment by kaori-seasons** [comment]
i want to try to fix it

**Comment by kaori-seasons** [comment]
I have reproduced the problem according to the steps you gave, and found that the current version does not perform heartbeat detection on the session, which is fixed in dubbo-go@v3. The code snippet is:

```
decodeResult, drOK := pkg.(*remoting.DecodeResult)
	if !drOK || decodeResult == ((*remoting.DecodeResult)(nil)) {
		logger.Errorf("illegal package{%#v}", pkg)
		return
	}
	if !decodeResult.IsRequest {
		res := decodeResult.Result.(*remoting.Response)
		if res.Event {
			logger.Debugf("get rpc heartbeat response{%#v}", res)
			if res.Error != nil {
				logger.Errorf("rpc heartbeat response{error: %#v}", res.Error)
			}
			res.Handle()
			return
		}
		logger.Errorf("illegal package but not heartbeat. {%#v}", pkg)
		return
	}
	req := decodeResult.Result.(*remoting.Request)

```

see code:  https://github.com/apache/dubbo-go/blob/1e82194facaf976c29c14ac92df94deacc89ff1c/remoting/getty/listener.go#L95

Maybe we can refer here?

**Comment by complone** [comment]
Maybe you need to update the version of dubbo-go?
