### ISSUE TITLE
报  call triple server error = service was not found upstream even though it should have been there: service not found; service discovery error

### ISSUE THREAD

**Issue by nicktming** [apache/dubbo-go-pixiu#523]
syntax = "proto3";

import "k8s.io/api/core/v1/generated.proto";

package test;

option go_package = "./;test";

service TestInterface {
  rpc GetTest (TestRequest) returns (TestResponse) {
  }
}

message TestRequest {
  string uid = 1;
  Test test = 2;
}

message TestResponse {
  optional bool success = 1;
}

message Test {
  optional string name = 1;
  optional k8s.io.api.core.v1.Pod  Pod = 2;
}

**What happened**:

当proto3引用proto2文件起的dubbo triple服务  p.call 报 client call err: call triple server error = service was not found upstream even though it should have been there: service not found; service discovery error

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by AlexStocks** [comment]
![image](https://user-images.githubusercontent.com/7959374/202607461-aaf2874f-716b-424a-8964-dcd832172a86.png)

 根本原因：k8s 用了 gogo 组织的 gogoprotobuf 编译 pb，而 dubbogo 的 triple 使用的是go官方使用的 protobuf，导致协议不通。

**Comment by mark4z** [comment]
使用本地导入的protoset有可能解决该问题

**Comment by mark4z** [comment]
该问题是由于gprc reflection无法识别gogoprotoc生成的pb。
可能的解决方案，对于此种情况，为triple的filter增加一个配置的路径，用来加载protoset文件。这样对于不兼容的情况，不使用gprc reflection来避免问题。
但同时，需要保留gprc reflection的能力。

可以参考的项目：https://github.com/fullstorydev/grpcurl（拥有以上两种能力）
![image](https://user-images.githubusercontent.com/36187602/204498412-9d380dd9-0728-4fda-b295-bb728b7131c5.png)

**Comment by mark4z** [comment]
cc @jielun1995

**Comment by ShawnHXH** [comment]
consider closing

**Comment by mark4z** [comment]
close via #548
