### ISSUE TITLE
piuxiu  http -> triple 传头信息 

### ISSUE THREAD

**Issue by nicktming** [apache/dubbo-go-pixiu#525]
**What happened**:

http的header 无法通过pixiu 传到 代理的后端triple服务

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by mark4z** [comment]
如果能替换掉grpc-http-proxy是最好的

**Comment by AlexStocks** [comment]
![image](https://user-images.githubusercontent.com/7959374/202730960-9a36df00-40ea-457c-b0c0-25b4ee58638e.png)

**Comment by mark4z** [comment]
对于 #525 错误的原因是库`github.com/mercari/grpc-http-proxy`的bug，该库直接忽略了传输的MD，导致matedata无法传递。使用到的该库的代码并不多，建议直接去掉该库的依赖。在pixiu内部实现一个泛化调用。

**Comment by mark4z** [comment]
可能会和 #523 有代码上的依赖

**Comment by mark4z** [comment]
cc @jielun1995

**Comment by jielun1995** [comment]
ok


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月29日(星期二) 晚上10:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [apache/dubbo-go-pixiu] piuxiu  http -&gt; triple 传头信息  (Issue #525)




 
cc @jielun1995

**Comment by wesleywu** [comment]
> 如果能替换掉grpc-http-proxy是最好的

同意，建议参考 dubbo-go 的 proxy 和 RPCService 实现。

我在实际测试中还发现，grpc-http-proxy 在调用 rpc 方法时，无法正确传递 trace.recodingSpan 的 ctx，导致从 pixiu -> dubbo-go provider 的链路跟踪失效。

**Comment by ShawnHXH** [comment]
consider closing

**Comment by mark4z** [comment]
close via https://github.com/apache/dubbo-go-pixiu/pull/548
