### ISSUE TITLE
How can we get the http Cookie when dgp.filter.http.dubboproxy has been chosen

### ISSUE THREAD

**Issue by river0828** [apache/dubbo-go-pixiu#598]
**What would you like to be added**:
I would like to ask a module which can be used to transform the http request with its Cookie to the Dubbo request so that I can get the Cookie in my Dubbo cluster. The optimal way of usage is that I choose the dgp.filter.http.dubboproxy and at the same time I can get the Cookie with the request body, then I can send then response with the Cookie too. In simple terms, I would like to find a way to add the http Cookie within the whole system which has used the Pixiu as the gateway and the dgp.filter.http.dubboproxy as the filter.

**Why is this needed**:
Because of the way of authentication we has chosen, we must get the Cookie almost everywhere in the system. But now I have no idea about how to get the Cookie through the dgp.filter.http.dubboproxy filter in Pixiu.

**Comment by baerwang** [comment]
https://github.com/apache/dubbo-go-pixiu/blob/804628011ed9dd9e67d063234b123a8a1390bb0a/pixiu/pkg/filter/http/remote/call.go#L120

you can get cookie in this code

```go
 c.Request.Header.Get("Cookie")
```
