### ISSUE TITLE
github.com/opentrx/seata-golang/v2 unknown revision v2.0.5

### ISSUE THREAD

**Issue by potterhe** [apache/dubbo-go-pixiu#627]
**What happened**:
When executing `make build`, an error is reported

```
...
go: downloading github.com/opentrx/seata-golang/v2 v2.0.5
../../pkg/filter/seata/branch_transaction_service.go:31:2: reading github.com/opentrx/seata-golang/go.mod at revision v2.0.5: unknown revision v2.0.5
...
make: *** [build] Error 1
```

**What you expected to happen**:
build build successful

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

go version go1.22.1 darwin/arm64
tag: v1.0.0-rc4
branch: develop

**Comment by AlexStocks** [comment]
这个 repo 已经不存在了 @mark4z 相关代码可以考虑删掉

**Comment by mark4z** [comment]
I will fix it later
