### ISSUE TITLE
lost the origin URL path in filter.

### ISSUE THREAD

**Issue by williamfeng323** [apache/dubbo-go-pixiu#76]
**What happened**:
There is a bug in replacepath filter. In the filter, it will replace the original URL path with the configured target path. It makes the URI parameters value missing. So before this bug fixed, the URI analysis will not be able to use(for HTTP-to-http proxy).
**What you expected to happen**:
The origin URL should be retained. 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by zouyx** [comment]
Fighting bro!

**Comment by cityiron** [comment]
path rewrite, include  host, uri, schema,headers

**Comment by cityiron** [comment]
@williamfeng323 This issue is only to support replacepath?
